import type {
  CorporateContent,
  HomepageContent,
  TestimonialsContent,
} from "@/types/cms-content";
import { storeImages } from "@/data/store-images";

export const defaultHomepageContent: HomepageContent = {
  heroBanners: [
    {
      id: "visiting-cards",
      href: "/products/visiting-cards",
      label: "Visiting Cards",
      sub: "300gsm texture boards · From ₹499",
      cta: "Design & order",
      image: storeImages.visitingCards,
    },
    {
      id: "photo-print",
      href: "/products/photo-print-with-frame",
      label: "Photo Prints",
      sub: '6"×4" to 12"×18" · Same-day pickup',
      cta: "Print photos",
      image: storeImages.photoPrint,
    },
    {
      id: "signage",
      href: "/products/banners-vinyl-stickers",
      label: "Signages & Wall Graphics",
      sub: "Indoor & outdoor branding",
      cta: "Get a quote",
      image: storeImages.signageWallMural,
    },
  ],
  perks: [
    { id: "same-day", label: "Same-day pickup", sub: "On select products", gradient: "from-amber-400 to-brand-500" },
    { id: "btm", label: "BTM walk-in store", sub: "Opp. Metro Pillar 154", gradient: "from-sky-400 to-blue-500" },
    { id: "design", label: "Design support", sub: "Artwork & proofs", gradient: "from-violet-400 to-purple-500" },
    { id: "colour", label: "Colour accurate", sub: "Brand-matched print", gradient: "from-emerald-400 to-teal-500" },
  ],
  howItWorks: [
    {
      id: "pick",
      step: "01",
      title: "Pick a product",
      body: "Browse categories or shop by business need — every item shows starting price and turnaround.",
      icon: "Package",
    },
    {
      id: "customise",
      step: "02",
      title: "Customise & upload",
      body: "Choose size, finish, and quantity. Email or WhatsApp print-ready files, or visit us with a USB.",
      icon: "Palette",
    },
    {
      id: "print",
      step: "03",
      title: "We print & proof",
      body: "Our team reviews artwork, confirms colour and stock, then runs your job on digital or offset.",
      icon: "Printer",
    },
    {
      id: "pickup",
      step: "04",
      title: "Pickup or delivery",
      body: "Collect at BTM 2nd Stage same day on select items, or coordinate delivery across Bengaluru.",
      icon: "Truck",
    },
  ],
  promises: [
    {
      id: "custom",
      title: "Customised your way",
      body: "Choose size, finish, and quantity on every product — upload artwork or brief our design desk for proofs.",
      icon: "Sparkles",
    },
    {
      id: "satisfaction",
      title: "100% satisfaction focus",
      body: "We check files before print, match brand colours where needed, and call you if anything needs fixing.",
      icon: "Heart",
    },
    {
      id: "trust",
      title: "Production you can trust",
      body: "Digital & offset capability under one roof at BTM — same quality whether you walk in or order online.",
      icon: "ShieldCheck",
    },
  ],
  faqs: [
    {
      id: "same-day",
      question: "Does Fast Prints offer same-day delivery?",
      answer:
        "Yes — selected products like flyers, pamphlets, photo prints, and document prints can be ready for same-day pickup at our BTM Layout store.",
    },
    {
      id: "small-qty",
      question: "Can I order small quantities?",
      answer:
        "Absolutely. Many products start from single pieces (photo prints, passport photos) or low MOQs (100 visiting cards, 25 ID cards).",
    },
    {
      id: "files",
      question: "How do I send my design files?",
      answer:
        "Email print-ready PDFs to fastprintsbtm@gmail.com, WhatsApp +91 91647 79922, or walk in with a USB drive at the store.",
    },
    {
      id: "popular",
      question: "What are your most popular products?",
      answer:
        "Visiting cards, pamphlets, ID cards, lanyards, photo prints, calendars, and wall signage are our top sellers.",
    },
  ],
  shopNeeds: [
    { id: "education", title: "Education & Campus", href: "/products?category=stationery", image: storeImages.receiptBooks },
    { id: "startup", title: "Startup Branding", href: "/products?category=business-essentials", image: storeImages.visitingCards },
    { id: "events", title: "Events & Promotions", href: "/products?category=large-format", image: storeImages.signageWallMural },
    { id: "retail", title: "Retail & Packaging", href: "/products?category=packaging", image: storeImages.presentationEnvelopes },
    { id: "cafe", title: "Cafe & Restaurant", href: "/products?category=marketing-materials", image: storeImages.pamphletGrocery },
    { id: "boutique", title: "Boutique & Fashion", href: "/products?category=packaging", image: storeImages.presentationEnvelopesGift },
    { id: "wedding", title: "Weddings", href: "/products?category=events", image: storeImages.pamphletInvitation },
    { id: "corporate", title: "Corporate ID Kits", href: "/products/id-cards-lanyards", image: storeImages.idCardLanyardSet },
  ],
  budgetRanges: [
    {
      id: "under-500",
      label: "Under ₹500",
      range: "0-499",
      sub: "Photo prints, keychains & more",
      tone: "from-emerald-50 to-teal-50 border-emerald-100",
    },
    {
      id: "500-999",
      label: "₹500 – ₹999",
      range: "500-999",
      sub: "Visiting cards, pamphlets",
      tone: "from-brand-50 to-amber-50 border-brand-200",
    },
    {
      id: "1000-2499",
      label: "₹1,000 – ₹2,499",
      range: "1000-2499",
      sub: "Letterheads, calendars, IDs",
      tone: "from-sky-50 to-blue-50 border-sky-100",
    },
    {
      id: "2500-plus",
      label: "₹2,500+",
      range: "2500-999999",
      sub: "Signage, bulk & corporate",
      tone: "from-violet-50 to-purple-50 border-violet-100",
    },
  ],
  facility: {
    eyebrow: "Our print floor",
    title: "Professional equipment. Premium output.",
    body: "Walk into BTM or order online — your job runs on the same production line. Digital, offset, large format, and finishing — all under one roof.",
    overviewImage: storeImages.servicesOverview,
    stats: [
      { id: "years", value: "15+", label: "Years in print" },
      { id: "services", value: "40+", label: "Services" },
      { id: "same-day", value: "Same day", label: "On select jobs" },
      { id: "hub", value: "BTM", label: "Production hub" },
    ],
    machines: [
      {
        id: "digital",
        name: "Digital production press",
        tag: "Everyday jobs",
        description: "Visiting cards, brochures, flyers, and short-run corporate print with fast turnaround.",
        specs: ["Up to 300gsm", "Same-day select jobs", "Colour-managed output"],
        image: "/images/bulk-multicolor-print.png",
      },
      {
        id: "offset",
        name: "Offset & multicolour",
        tag: "Bulk volume",
        description: "High-volume pamphlets, books, and stationery with consistent colour across thousands of copies.",
        specs: ["500+ quantity", "Art paper stocks", "Pantone matching"],
        image: "/images/pamphlet-multicolor.png",
      },
      {
        id: "large-format",
        name: "Large format & signage",
        tag: "Brand visibility",
        description: "Banners, wall graphics, flex, and indoor signage for retail, events, and office branding.",
        specs: ["Wide format roll", "Indoor & outdoor", "Custom sizes"],
        image: "/images/signage-wall-mural.png",
      },
      {
        id: "finishing",
        name: "Finishing & ID production",
        tag: "Ready to use",
        description: "Lamination, binding, die-cut, ID card printing, and lanyard assembly under one roof.",
        specs: ["ID + lanyard kits", "Lamination", "Custom packaging"],
        image: "/images/id-card-lanyard-set.png",
      },
    ],
  },
  brandShowcase: {
    eyebrow: "Think Printing… Think Us",
    title: "Your complete print partner in Bengaluru",
    body: "From visiting cards to wall murals — Fast Prints handles design, production, and pickup at BTM Layout with same-day options on select jobs.",
    image: storeImages.servicesOverview,
    services: [
      "Digital & Offset Print",
      "Visiting Cards & Letterheads",
      "ID Cards & Lanyards",
      "Calendars & Photo Print",
      "Signages & Wall Graphics",
      "Pamphlets & Bulk Print",
    ],
  },
};

export const defaultTestimonialsContent: TestimonialsContent = {
  stats: {
    averageRating: 4.9,
    totalReviews: "500+",
    repeatCustomers: "85%",
    yearsServing: "15+",
  },
  items: [
    {
      id: "priya-marketing",
      name: "Priya S.",
      role: "Marketing Manager",
      company: "Tech startup, Koramangala",
      location: "Bengaluru",
      rating: 5,
      product: "Pamphlets & standees",
      featured: true,
      text: "Our launch flyers and standees were ready faster than the venue setup. Colour matched the PDF proof — no surprises at pickup from BTM.",
    },
    {
      id: "arjun-founder",
      name: "Arjun M.",
      role: "Founder",
      company: "SaaS company",
      location: "BTM Layout",
      rating: 5,
      product: "Visiting cards & apparel",
      featured: true,
      text: "Cards and team tees in one place. Fast Prints handled sizing and artwork checks so we could focus on demos. Same-day pickup saved us.",
    },
    {
      id: "neha-wedding",
      name: "Neha R.",
      role: "Bride-to-be",
      location: "Jayanagar",
      rating: 5,
      product: "Invitation folio",
      featured: true,
      text: "Invitation folio with premium finish — guests keep asking where we printed. The team called to confirm paper stock before running the job.",
    },
    {
      id: "ramesh-retail",
      name: "Ramesh K.",
      role: "Store Owner",
      company: "Grocery retail, BTM",
      location: "BTM 2nd Stage",
      rating: 5,
      product: "Pamphlets & banners",
      text: "Weekly offer pamphlets and shop banners at fair bulk rates. Delivery across Bengaluru when we cannot pick up — very reliable.",
    },
    {
      id: "anita-hr",
      name: "Anita V.",
      role: "HR Executive",
      company: "Corporate office",
      location: "Electronic City",
      rating: 5,
      product: "ID cards & lanyards",
      text: "200 employee ID kits with lanyards — artwork review, proof on WhatsApp, and delivery on the promised date. Exactly what admin teams need.",
    },
    {
      id: "karthik-cafe",
      name: "Karthik D.",
      role: "Cafe Owner",
      location: "HSR Layout",
      rating: 5,
      product: "Menu cards & signage",
      text: "Menu redesign and counter signage done in two days. Walked in near Metro Pillar 154 — easy to find, friendly team.",
    },
    {
      id: "divya-school",
      name: "Divya P.",
      role: "School Coordinator",
      location: "Bannerghatta Rd",
      rating: 5,
      product: "Certificates & ID cards",
      text: "Annual day certificates and student ID batches every year. Consistent quality and patient with our last-minute changes.",
    },
    {
      id: "suresh-realestate",
      name: "Suresh N.",
      role: "Property Consultant",
      location: "Bengaluru",
      rating: 4,
      product: "Visiting cards & brochures",
      text: "Premium visiting cards and project brochures for client meetings. Good stock options and honest turnaround estimates.",
    },
    {
      id: "meena-boutique",
      name: "Meena L.",
      role: "Boutique Owner",
      location: "JP Nagar",
      rating: 5,
      product: "Tags & packaging",
      text: "Branded tags and gift envelopes for our festive collection. Small quantity was not a problem — they treated it professionally.",
    },
  ],
};

export const defaultCorporateContent: CorporateContent = {
  heroEyebrow: "Corporate & bulk",
  heroTitle: "One partner for office print & brand collateral",
  heroBody:
    "Visiting cards, ID kits, letterheads, pamphlets, and signage — tailored to your quantity. Pricing is shared after you request a quote.",
  heroImage: storeImages.idCardLanyardSet,
  features: [
    {
      id: "quote",
      title: "Bulk quote & MOQ",
      body: "Share quantity and specs — we respond with volume pricing, proofs, and a clear timeline. No checkout pressure.",
    },
    {
      id: "brand",
      title: "Brand consistency",
      body: "Matched colours across visiting cards, letterheads, envelopes, and campaign print for one brand look.",
    },
    {
      id: "artwork",
      title: "Artwork support",
      body: "Upload print-ready files or brief our desk. We review bleed, resolution, and colour before production.",
    },
    {
      id: "id",
      title: "ID & onboarding kits",
      body: "Employee ID cards, lanyards, and welcome packs — ideal for HR teams and new joiner batches.",
    },
    {
      id: "campaign",
      title: "Campaign print",
      body: "Pamphlets, standees, and event collateral with flexible quantities for marketing and field teams.",
    },
    {
      id: "support",
      title: "Dedicated follow-up",
      body: "A named contact from our BTM team — phone, WhatsApp, and email until delivery is confirmed.",
    },
  ],
  solutions: [
    { id: "hr", title: "HR & admin", body: "ID kits, letterheads, and onboarding stationery for growing teams.", icon: "Users" },
    { id: "marketing", title: "Marketing", body: "Pamphlets, signage, and launch print with volume-friendly pricing.", icon: "BarChart3" },
    { id: "offices", title: "Offices & retail", body: "Consistent brand touchpoints across branches and store fronts.", icon: "Building2" },
    { id: "events", title: "Events & gifting", body: "Custom envelopes, calendars, and branded collateral for milestones.", icon: "Gift" },
  ],
};
